env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
  matrix:
    - name: freebsd-16
      freebsd_instace:
         image_family: freebsd-16-0-snap
    - name: freebsd15-0-release-amd64
      freebsd_instance:
         image: freebsd-15-0-release-amd64-ufs
    - name: freebsd14-3-release-amd64
      freebsd_instance:
         image: freebsd-14-3-release-amd64-ufs
    - name: freebsd13-5-release-amd64
      freebsd_instance:
         image: freebsd-13-5-release-amd64
  src_script:
    - test -f /usr/src/Makefile
